 
INSERT INTO DELTATRA_CLIENT_ADMIN.CA_MARCA (LABEL) VALUES 
 ('No Selection'),
 ('AGORA'),
 ('APLUS'),
 ('APOLLO'),
 ('ARMSTRONG'),
 ('ASCENSO'),
 ('BARUM'),
 ('BELSHINA'),
 ('BF GOODRICH'),
 ('BFGOODRICH'),
 ('BRIDGESTONE'),
 ('CEAT'),
 ('CONTI RE'),
 ('CONTINENTAL'),
 ('CULTOR'),
 ('DAYTON'),
 ('DEBICA'),
 ('DIPLOMAT'),
 ('DUNLOP'),
 ('FALKEN'),
 ('FEDERAL'),
 ('FIRESTONE'),
 ('FORMULA'),
 ('FULDA'),
 ('GENERAL'),
 ('GISLAVED'),
 ('GITI'),
 ('GOLDLINE'),
 ('GOODYEAR'),
 ('GREENTRAC'),
 ('GRIPMAX'),
 ('GT RADIAL'),
 ('GTK'),
 ('HANKOOK'),
 ('HIFLY'),
 ('IMPERIAL'),
 ('INSA TURBO'),
 ('JINYU'),
 ('KABAT'),
 ('KAMA'),
 ('KAPSEN'),
 ('KELLY'),
 ('KENDA'),
 ('KINGSTAR'),
 ('KLEBER'),
 ('KORMORAN'),
 ('KUMHO'),
 ('LAUFENN'),
 ('LING LONG'),
 ('LONG MARCH'),
 ('MATADOR'),
 ('MAXXIS'),
 ('MICHELIN'),
 ('MINERVA'),
 ('MIRAGE'),
 ('MITAS'),
 ('NANKANG'),
 ('NEXEN'),
 ('NOKIAN'),
 ('NORDMAN-NOK'),
 ('NOVEX'),
 ('OMSZK'),
 ('OZKA'),
 ('PAXARO'),
 ('PETLAS'),
 ('PIRELLI'),
 ('PREMIORRI'),
 ('RADAR'),
 ('REMIX'),
 ('RIKEN'),
 ('ROSAVA'),
 ('ROSJA_WNP'),
 ('SAILUN'),
 ('SAVA'),
 ('SEBRING'),
 ('SEHA'),
 ('SEIBERLING'),
 ('SEMPERIT'),
 ('SUMITOMO'),
 ('TAURUS'),
 ('TIGAR'),
 ('TORQUE'),
 ('TOYO'),
 ('TRELLEBORG'),
 ('TRIANGLE'),
 ('TRISTAR'),
 ('UNIROYAL'),
 ('VIKING'),
 ('VOLTYRE'),
 ('VOYAGER'),
 ('VREDESTEIN'),
 ('WESTLAKE'),
 ('YOKOHAMA');